### PR TITLE
locally store syscall table rather than pulling from the interwebs

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Noratrieb** [comment]
whats the benefit of this? when the tables dont change, i dont need to regenerate them. and when they do change, having the old copy locally doesnt get me anything.

**Comment by ghost** [comment]
how often do they change

**Comment by Noratrieb** [comment]
when linus adds new syscalls

**Comment by Noratrieb** [comment]
not that i really care then but the point stands, the generated code is checked in and i dont see why id want the json checked in too. if you cant reproduce it in the future because the site is offline that doesnt matter

**Comment by ghost** [comment]
ohk

**Pull request closed without merging**
